version: "3"
services:
    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:latest
        restart: always
        volumes:
            - ${HOST_PATH}/redis:/data
        networks:
            default:
                ipv4_address: ${PROJECT_SUBNET}.5
    mariadb:
        container_name: ${PROJECT_NAME}_mariadb
        build: mariadb
        image: mariadb
        restart: always
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${HOST_PATH}/mysql:/var/lib/mysql
            - ${HOST_PATH}/dumps:/dumps
        #ports:
            #- "3306:3306"
            #- "3306:3306"
        networks:
            default:
                ipv4_address: ${PROJECT_SUBNET}.4
    php:
        container_name: ${PROJECT_NAME}_php
        build: php
        image: php
        restart: always
        environment:
            - USER_ID=${USER_ID:-www-data}
            - GROUP_ID=${GROUP_ID:-www-data}
            - HOSTNAME=host
            - FPM_LISTEN_ALLOWED_CLIENTS=nginx
            - FPM_HOST=${FPM_HOST:-0.0.0.0}
            - FPM_PORT=${FPM_HOST:-9000}
            - FPM_CATCH_WORKER_OUTPUT=${FPM_CATCH_WORKER_OUTPUT:-yes}
            - FPM_SECURITY_LIMIT_EXTENSIONS=${FPM_SECURITY_LIMIT_EXTENSIONS:-.php}
            - FPM_PM=${FPM_PM:-static}
            - FPM_PM_START_SERVERS=${FPM_PM_START_SERVERS:-10}
            - FPM_PM_MAX_CHILDREN=${FPM_PM_MAX_CHILDREN:-10}
            - FPM_PM_MIN_SPARE_SERVERS=${FPM_PM_MIN_SPARE_SERVERS:-1}
            - FPM_PM_MAX_SPARE_SERVERS=${FPM_PM_MAX_SPARE_SERVERS:-3}
            - FPM_PM_MAX_REQUESTS=${FPM_PM_MAX_REQUESTS:-1000}
            - FPM_PM_STATUS_PATH=${FPM_PM_STATUS_PATH:-/fpm-status}
            - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-30}
            - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-60}
            - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-64M}
            - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-10M}
            - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
            - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-Off}
            - PHP_LOG_ERRORS=${PHP_LOG_ERRORS:-On}
        volumes:
            - ${HOST_PATH}:/var/www/host
            - ${LIB_PATH}:/var/www/lib
        depends_on: 
            - mariadb
            - redis
        networks:
            default:
                ipv4_address: ${PROJECT_SUBNET}.3
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build: nginx
        image: nginx
        restart: always
        environment:
            - USER_ID=${USER_ID:-www-data}
            - GROUP_ID=${GROUP_ID:-www-data}
            - HOSTNAME=host
            - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
            - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
            - NGINX_MULTI_ACCEPT=${NGINX_MULTI_ACCEPT:-on}
        volumes:
            - ${HOST_PATH}:/var/www/host
            - ${LIB_PATH}:/var/www/lib
        depends_on: 
            - php
        #ports:
            #- "80:80"
            #- "443:443"
        networks:
            default:
                ipv4_address: ${PROJECT_SUBNET}.2
networks:
    default:
        ipam:
            config:
                - subnet: ${PROJECT_SUBNET}.0/24
