version: "3.5"
services:
  ## --------------------------------------------
  ## | PHP
  ## --------------------------------------------

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ${PATH_TO_WEBBHUSET}:/var/www/webbhuset.fi
      - ${PATH_TO_LIB}:/var/www/lib
      # - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./symlinks.sh:/var/www/symlinks.sh
    container_name: wh-php
    working_dir: /var/www
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    networks:
      - wh

  ## --------------------------------------------
  ## | Nginx
  ## --------------------------------------------

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: wh-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ${PATH_TO_WEBBHUSET}:/var/www/webbhuset.fi
      - ${PATH_TO_LIB}:/var/www/lib
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wh

  ## --------------------------------------------
  ## | MySql
  ## --------------------------------------------

  mysql:
    image: mysql:8.0.30
    container_name: wh-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "wh"
    command: --sql_mode=""
    restart: always
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/tmp:/docker-entrypoint-initdb.d
    ports:
      - "33066:3306"
    networks:
      - wh

  ## --------------------------------------------
  ## | PhpMyAdmin
  ## --------------------------------------------

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wh-phpmyadmin
    depends_on:
      - mysql
    ports:
      - "23005:80"
    environment:
      - PMA_HOST=wh-mysql
    volumes:
      - ./phpmyadmin/save/:/var/www/phpmyadmin/save/
      - ./phpmyadmin/upload/:/var/www/phpmyadmin/upload/
      - ./phpmyadmin/config.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - wh

networks:
  wh:
    driver: bridge
